declare const install: (Vue: any) => void;
export * from './components/bsForm';
export * from './components/bsCascader';
export * from './components/bsCheckbox';
export * from './components/bsDate';
export * from './components/bsDateRange';
export * from './components/bsInput';
export * from './components/bsNumber';
export * from './components/bsNumberRange';
export * from './components/bsRadio';
export * from './components/bsSelect';
export * from './components/bsSwitch';
export * from './components/bsText';
export * from './components/bsTable';
export * from './components/bsButtons';
export default install;
