export interface rulesIn {
    amt: [any, string];
    digits: [any, string];
    trim: [any, string];
    positivedigits: [any, string];
    letters: [any, string];
    date: [any, string];
    time: [any, string];
    email: [any, string];
    url: [any, string];
    qq: [any, string];
    IDcard: [any, string];
    IDcardNew: [any, string];
    tel: [any, string];
    mobile: [any, string];
    zipcode: [any, string];
    chinese: [any, string];
    username: [any, string];
    password: [any, string];
    msgCode: [any, string];
    cvv2: [any, string];
    creditcardexp: [any, string];
    bankcard: [any, string];
    chkmoney: [any, string];
    realname: [any, string];
    percent: [any, string];
    chinese20: [any, string];
    chinese18: [any, string];
    chinese10: [any, string];
    chinese64: [any, string];
    chinese50: [any, string];
    chinese1000: [any, string];
    arbitrarily30to1000: [any, string];
    bizcode: [any, string];
}
declare const commonRules: rulesIn;
export declare function checkIdNo(value: string, callback: any): void;
export declare function checkEmail(value: string, callback: any): void;
export declare function checkPhoneNo(value: string, callback: any): void;
export declare function checkAmt(value: string, callback: any): void;
export declare function checkBankCard(value: string, callback: any): void;
export declare function checkName(value: string, callback: any): void;
export declare function checkChannel(value: string, callback: any): void;
export declare function positivedigits(value: string, callback: any): void;
export declare function checkNumber(value: string, callback: any): void;
export declare function checkPercent(value: string, callback: any): void;
export declare function checkPhoneNull(value: string, callback: any): void;
export declare function checkNumberNull(value: string, callback: any): void;
export declare function checkAmtNull(value: string, callback: any): void;
export declare function checkEmailNull(value: string, callback: any): void;
export declare function checkBizcode(value: string, callback: any): void;
export { commonRules };
